version: 0.2

env:
  parameter-store:
    ACM_CERTIFICATE_ARN: "ACMcertification"   # SSM parameter for ACM Certificate ARN
    HOSTED_ZONE_ID: "HostedZoneID"  # SSM parameter for Hosted Zone ID
  variables:
    DOMAIN_NAME: "luxabaya.com"  # Hardcoded domain name
    BUCKET_NAME: "theabayacollection-bucket"  # S3 bucket name

phases:
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - echo "Running pre-build commands"

  build:
    commands:
      - echo "Building CloudFormation Stack"
      
  post_build:
    commands:
      - echo "CloudFormation Stack creation triggered"
      - aws cloudformation describe-stacks --stack-name my-pipeline-stack

artifacts:
  files:
    - '**/*'
