version: 0.2

env:
  variables:
    DOMAIN_NAME: "luxabaya.com"
    BUCKET_NAME: "theabayacollection-bucket"

phases:
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - echo "Installing dependencies, if any"
      # Fetching ACM Certificate ARN and Hosted Zone ID from Parameter Store
      - echo "Fetching ACM Certificate ARN and Hosted Zone ID from Parameter Store"
      - |
        ACM_CERTIFICATE_ARN=$(aws ssm get-parameter --name ACMcertification --query 'Parameter.Value' --output text)
        export ACM_CERTIFICATE_ARN
      - |
        HOSTED_ZONE_ID=$(aws ssm get-parameter --name HostedZoneID --query 'Parameter.Value' --output text)
        export HOSTED_ZONE_ID
      - echo "ACM Certificate ARN: $ACM_CERTIFICATE_ARN"
      - echo "Hosted Zone ID: $HOSTED_ZONE_ID"


  build:
    commands:
      - echo "Deploying CloudFormation stack"
      - aws cloudformation create-stack --stack-name pipeline-stack-dev \
          --template-body file://s3_static_web.yml \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameters ParameterKey=DomainName,ParameterValue=$DOMAIN_NAME \
                       ParameterKey=BucketName,ParameterValue=$BUCKET_NAME \
                       ParameterKey=ACMCertificateArn,ParameterValue=$ACM_CERTIFICATE_ARN \
                       ParameterKey=HostedZoneId,ParameterValue=$HOSTED_ZONE_ID
      - echo "Stack created successfully"

  post_build:
    commands:
      - echo "Uploading static website files to S3"
      - aws s3 cp index.html s3://$BUCKET_NAME/index.html --acl bucket-owner-full-control
      - aws s3 cp error.html s3://$BUCKET_NAME/error.html --acl bucket-owner-full-control

artifacts:
  files:
    - '**/*'
