version: 0.2

env:
  variables:
    BUCKET_NAME: "theabayacollection-bucket"

phases:
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - echo "No dependencies to install"

  build:
    commands:
      - echo "Uploading static website files to S3"
      - aws s3 cp index.html s3://$BUCKET_NAME/index.html --acl bucket-owner-full-control
      - aws s3 cp error.html s3://$BUCKET_NAME/error.html --acl bucket-owner-full-control

artifacts:
  files:
    - '**/*'
