version: 0.2

env:
  parameter-store:
    ACM_CERTIFICATE_ARN: "ACMcertification"
    HOSTED_ZONE_ID: "HostedZoneID"
  variables:
    DOMAIN_NAME: "luxabaya.com"
    BUCKET_NAME: "theabayacollection-bucket"

phases:
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - echo "Installing dependencies, if any"

  build:
    commands:
      - echo "Deploying CloudFormation stack"
      - aws cloudformation create-stack --stack-name pipeline-stack-dev \
          --template-body file://s3_static_web.yml \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameters \
            ParameterKey=DomainName,ParameterValue=luxabaya.com \
            ParameterKey=BucketName,ParameterValue=theabayacollection-bucket
      - echo "Stack created successfully"

  post_build:
    commands:
      - echo "Uploading static website files to S3"
      - aws s3 cp index.html s3://theabayacollection-bucket/index.html --acl bucket-owner-full-control
      - aws s3 cp error.html s3://theabayacollection-bucket/error.html --acl bucket-owner-full-control

artifacts:
  files:
    - '**/*'
