version: 0.2

env:
  variables:
    DOMAIN_NAME: "luxabaya.com"
    BUCKET_NAME: "theabayacollection-bucket"
  parameter-store:
    ACM_CERTIFICATE_ARN: "ACMcertification"  
    HOSTED_ZONE_ID: "HostedZoneID"            

phases:
  install:
    runtime-versions:
      python: 3.8  

  pre_build:
    commands:
      - echo "Preparing to create CloudFormation stack"
      - echo "Checking for the existence of template file"

  build:
    commands:
      - echo "Creating CloudFormation stack"
      - create-stack --stack-name pipeline-stack-web-app \
          --template-body file://app-repository-east-dev/s3_static_web.yml \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameters ParameterKey=DomainName,ParameterValue=$DOMAIN_NAME \
                       ParameterKey=BucketName,ParameterValue=$BUCKET_NAME \
                       ParameterKey=ACMCertificateArn,ParameterValue=$ACM_CERTIFICATE_ARN \
                       ParameterKey=HostedZoneId,ParameterValue=$HOSTED_ZONE_ID 
        - echo "CloudFormation stack created successfully"

  post_build:
    commands:
      - echo "Uploading static website files to S3"
      - aws s3 cp index.html s3://$BUCKET_NAME/index.html --acl bucket-owner-full-control
      - aws s3 cp error.html s3://$BUCKET_NAME/error.html --acl bucket-owner-full-control
      - echo "Static website files uploaded successfully"

artifacts:
  files:
    - '**/*'
