version: 0.2

env:
  variables:
    DOMAIN_NAME: "luxabaya.com"
    BUCKET_NAME: "theabayacollection-bucket"

phases:
  install:
    runtime-versions:
      python: 3.8  
    commands:
      - echo "Installing dependencies"

  pre_build:
    commands:
      - echo "Preparing to create CloudFormation stack"

  build:
    commands:
      - echo "Creating CloudFormation stack"
      - aws cloudformation create-stack --stack-name pipeline-stack-web-app \
        --template-body file://s3_static_web.yml \
        --capabilities CAPABILITY_NAMED_IAM \
        --parameters ParameterKey=DomainName,ParameterValue=$DOMAIN_NAME \
                     ParameterKey=BucketName,ParameterValue=$BUCKET_NAME
      - echo "CloudFormation stack created successfully"

  post_build:
    commands:
      - echo "Uploading static website files to S3"
      - aws s3 cp index.html s3://$BUCKET_NAME/index.html --acl bucket-owner-full-control
      - aws s3 cp error.html s3://$BUCKET_NAME/error.html --acl bucket-owner-full-control

artifacts:
  files:
    - '**/*'
