version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  
  pre_build:
    commands:
      - echo "reference here"
      - DOMAIN_NAME= luxabaya.com  
      - BUCKET_NAME= theabayacollection-bucket  
      - ACM_CERTIFICATE_ARN= aws ssm get-parameter --name "ACMcertification" --query "Parameter.Value" --output text
      - HOSTED_ZONE_ID= aws ssm get-parameter --name "HostedZoneID" --query "Parameter.Value" --output text

  build:
    commands:
      - echo "Creating CloudFormation stack"
      - aws cloudformation create-stack --stack-name pipelinestackwebapp --template-body file://s3_static_web.yml --parameters ParameterKey=DomainName,ParameterValue=DOMAIN_NAME ParameterKey=BucketName,ParameterValue=BUCKET_NAME ParameterKey=ACMCertificateArn,ParameterValue=ACM_CERTIFICATE_ARN ParameterKey=HostedZoneId,ParameterValue=HOSTED_ZONE_ID 

  post_build:
    commands:
      - echo "Uploading static website files to S3"
      - aws s3 cp index.html s3://$theabayacollection-bucket/index.html --acl bucket-owner-full-control
      - aws s3 cp error.html s3://theabayacollection-bucket/error.html --acl bucket-owner-full-control
      - echo "Static website files uploaded successfully"

artifacts:
  files:
    - '**/*'
