version: 0.2

version: 0.2

env:
  parameter-store:
    ACM_CERTIFICATE_ARN: "/my/ssm/path/ACMcertification"   # SSM parameter for ACM Certificate ARN
    HOSTED_ZONE_ID: "/my/ssm/path/HostedZoneID"  # SSM parameter for Hosted Zone ID
  variables:
    DOMAIN_NAME: "luxabaya.com"  # Hardcoded domain name
    BUCKET_NAME: "theabayacollection-bucket"  # S3 bucket name

phases:
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - echo "Running pre-build commands"

  build:
    commands:
      - echo "Building CloudFormation Stack"
      - aws cloudformation create-stack --stack-name my-pipeline-stack ^
          --template-body file://s3_static_web.yml ^
          --capabilities CAPABILITY_NAMED_IAM *
          --parameters ^
            ParameterKey=DomainName,ParameterValue=$DOMAIN_NAME ^
            ParameterKey=ACMCertificateArn,ParameterValue=$ACM_CERTIFICATE_ARN ^
            ParameterKey=HostedZoneId,ParameterValue=$HOSTED_ZONE_ID ^
            ParameterKey=BucketName,ParameterValue=$BUCKET_NAME

  post_build:
    commands:
      - echo "CloudFormation Stack creation triggered"
      - aws cloudformation describe-stacks --stack-name my-pipeline-stack

artifacts:
  files:
    - '**/*'
