version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  # Ensure Python is available

  pre_build:
    commands:
      - python --version  # Verify Python version
      - echo "Cloning the repository..."
      - git clone https://github.com/your-username/your-repository.git
      - cd your-repository
      - echo "Validating CloudFormation template..."
      - aws cloudformation validate-template --template-body file://s3_static_web.yml --region us-east-1
  build:
    commands:
      - echo "Creating CloudFormation stack..."
      - aws cloudformation create-stack \
          --stack-name mypipelinestack \
          --template-body file://s3_static_web.yml \
          --region us-east-1 \
          --capabilities CAPABILITY_NAMED_IAM
      - echo "Waiting for stack creation to complete..."
      - aws cloudformation wait stack-create-complete --stack-name my-static-website-stack
 
  post_build:
    commands:
      - echo "Uploading website files to S3..."
      - aws s3 cp index.html s3://theabayacollection-bucket/index.html --acl bucket-owner-full-control
      - aws s3 cp error.html s3://theabayacollection-bucket/error.html --acl bucket-owner-full-control
      - echo "Files uploaded successfully."

artifacts:
  files:
    - '**/*'

